version: "3.6"
services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    env_file:
      - .docker/env
      - .docker/app/env
    working_dir: /home/appuser/works
    command: ./bin/rails s -b 0.0.0.0
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    depends_on:
      - redis
      - db
    volumes:
      - ./:/home/appuser/works
      - bundle:/usr/local/bundle
      - node_modules:/home/appuser/works/node_modules
  redis:
    image: redis:5-alpine
    env_file:
      - .docker/env
    ports:
      - 6379:6379
  db:
    image: postgres:12-alpine
    env_file:
      - .docker/env
      - .docker/db/env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgres/data
      - .docker/db/initdb.d:/docker-entrypoint-initdb.d
      - ./tmp:/opt/tmp
volumes:
  bundle:
  node_modules:
  pgdata:
